[build]
functions = "src/functions"
publish = "src/public"

[[redirects]]
from = "/"
to = "https://github.com/kalkspace/zammad-slack-gateway"
status = 301
force = true

[[redirects]]
from = "/webhook"
to = "/.netlify/functions/webhook"
status = 200
force = true
